logging:
  file:
    path: logs
  level:
    root: info
  config: classpath:logback-spring.xml


server:
  port: 12455


spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://47.98.178.104:3306/Bahncard?useUnicode=true&autoReconnect=TRUE&characterEncoding=utf-8&useSSL=false
      username: root
      password: yyyyyyyyy
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        idle-timeout: 600000
        maximum-pool-size: 15
        auto-commit: true
        pool-name: Master-HikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
    slave1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://149.129.119.32:3306/Bahncard?useUnicode=true&autoReconnect=TRUE&characterEncoding=utf-8&useSSL=false
      username: root
      password:ddddddd
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        idle-timeout: 600000
        maximum-pool-size: 15
        auto-commit: true
        pool-name: slave1-HikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
    slave2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://144.34.203.229:3306/Bahncard?useUnicode=true&autoReconnect=TRUE&characterEncoding=utf-8&useSSL=false
      username: root
      password: xxxxxxxx
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        idle-timeout: 600000
        maximum-pool-size: 15
        auto-commit: true
        pool-name: slave2-HikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1







  kafka:
    consumer:
      group-id: bahncard
      auto-offset-reset: earliest
      bootstrap-servers: 192.168.124.133:19092,192.168.124.134:19092,192.168.124.135:19092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 192.168.124.133:19092,192.168.124.134:19092,192.168.124.135:19092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      concurrency: 4
  redis:
    host: 144.34.203.229
    password: U39PqNh2TtjwCcadJmGQ
    port: 6379
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0

mybatis:
  type-aliases-package: me.superning.luntan.domain
  mapper-locations: classpath:mapper/*.xml
